name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint -d R0903,C0103,R0902,W0718,R0912,E0611,R0911,W0401 ./kernel
        pylint -d R0903,C0103,R0902,W0718,R0912,E0611,R0911,W0401 ./module
        pylint -d R0903,C0103,R0902,W0718,R0912,E0611,R0911,W0401 ./utils
        pylint -d R0903,C0103,R0902,W0718,R0912,E0611,R0911,W0401 server.py
